# dependabot.yml file with
# customized npm configuration

version: 1
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'auto-update'
      - 'auto-merge'
